### ISSUE TITLE
Cannot display Silverlight objects

### ISSUE THREAD

**Issue by Mistert99** [OceanAirdrop/WinFormsHTMLChromium#1]
When displaying a web page with Silverlight objects, a dialog box asks the user to install Microsoft Silverlight.

Please supply support for Silverlight objects.

Thank you

**Comment by OceanAirdrop** [comment]
Hi Mister99,

Unfortunately support for Silverlight is not there for Chromium. They are disabling NPAPI which means browser plugins such as Java and Silverlight will not run. 

Please see these articles from the chromium blog:

http://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html
https://www.chromium.org/developers/npapi-deprecation
https://threatpost.com/google-shuts-off-npapi-in-chrome/112295
